### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Soniafish**
林盈如,
http://3.18.227.207:3000/api/attractions?page=1
http://3.18.227.207:3000/api/attractions?page=0&keyword=藝術
http://3.18.227.207:3000/api/attraction/100

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
連結測試失敗哦 ~

**Comment by Soniafish** [comment]
林盈如, (已更新並重啟)
http://3.18.227.207:3000/api/attractions?page=1
http://3.18.227.207:3000/api/attractions?page=0&keyword=藝術
http://3.18.227.207:3000/api/attraction/100

**Review by cwpeng — CHANGES_REQUESTED** [review]
關鍵字請篩選景點的名稱 ~

**Comment by Soniafish** [comment]
林盈如, (關鍵字已改為篩選景點)
http://3.18.227.207:3000/api/attractions?page=1
http://3.18.227.207:3000/api/attractions?page=0&keyword=藝術
http://3.18.227.207:3000/api/attraction/100

**Review by cwpeng — APPROVED** [review]
Good. ~

**Pull request merged**
